# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddContributionDocs: false
AddCopierCI: false
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: false
AddLintCI: false
AddLychee: true
AddMacToCI: false
AddPrecommit: true
AddPrecommitUpdateCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: mcclellanio mcclellanio@fastmail.com
CheckExplicitImports: true
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
GitHubActionVersionAutoUpdate: none
JuliaCompatAutoUpdate: dependabot
JuliaIndentation: 4
JuliaMinCIVersion: '1.12'
JuliaMinVersion: '1.12'
License: MIT
LicenseCopyrightHolders: mcclellanio mcclellanio@fastmail.com
MarkdownIndentation: 2
PackageName: PracticalPkg
PackageOwner: mcclellanio
PackageUUID: f93ac9d6-c0e5-564d-9c20-a1d2b629210c
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: true
TestingStrategy: testitem_basic
UseCirrusCI: false
_src_path: /Users/mcclellm/.julia/packages/BestieTemplate/fOzc4
